; Object ids, such as the ids used in collision data; see CheckGameObjectCollision

DEF OBJ_ALLEYTRIGGER_FIRST_RUBYFIELD	EQU $11
DEF OBJ_ALLEYTRIGGER_LEFT_PRIMARY_RUBYFIELD	EQU $11
DEF OBJ_ALLEYTRIGGER_LEFT_SECONDARY_RUBYFIELD	EQU $12
DEF OBJ_ALLEYTRIGGER_RIGHT_PRIMARY_RUBYFIELD	EQU $13
DEF OBJ_ALLEYTRIGGER_RIGHT_SECONDARY_RUBYFIELD	EQU $14
DEF OBJ_ALLEYTRIGGER_INNERLEFT_PRIMARY_RUBYFIELD	EQU $15
DEF OBJ_ALLEYTRIGGER_INNERLEFT_SECONDARY_RUBYFIELD	EQU $16
